name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  test:
    uses: clambin/workflows/.github/workflows/libtest.yaml@go1.23
    secrets:
      codecov-token: ${{ secrets.CODECOV_TOKEN }}
  publish:
    needs: test
    uses: clambin/workflows/.github/workflows/release.yaml@go1.23
